export const DEPARTMENT_HEAD_OR_COUNSELLOR_GET_ALL_QUESTIONS =
  'DEPARTMENT_HEAD_OR_COUNSELLOR_GET_ALL_QUESTIONS';
export const USER_GET_ALL_QUESTIONS = 'USER_GET_ALL_QUESTIONS';
export const HOME_GET_ALL_QUESTIONS = 'HOME_GET_ALL_QUESTIONS';
export const DEPARTMENT_HEAD_GET_ALL_QUESTIONS = 'DEPARTMENT_HEAD_GET_ALL_QUESTIONS';
